travis:
  secure:
    BINSTAR_TOKEN: Zj67hkmXTnpJuldPyM5HweQc2ftjwvInvAtzTN2odCuXffYO/eUdLtHyEoqKSNUkGg8AUjsIsN9GMHQSqC+sDUhZLMNOWsAt4LgTDFAJDwBNLOFvmvlglYH9324BkJOdFgJXoaYfgcukjhycuCEi1ShLKJN0SjNdXI2O9nmpuPxiTCXQZNne/RdNn368U3HuNG6VsEFxb7Vm9QJcvg2x+tMgSpXkbXFbybjxhtf1t8hNuT7rS7R6PZZP4GyDWvboDZ81bBA74AJkD4ZYWAf9CLKQviBwkLPv+OqXrDYEVGwlNVh/qssModYjdmk/VHKu4sVdbgPP7RHk5GjGC4hh5j4C/u0tsJEG+UZewmqqeRnKVmnqWha5YVRKVj41xODMPmwX7AqqB80muwYMXiiTfGr7Kw8KSAV9OZyw0EHwd+oKH+G4hjAUryuWiCkpnjnPrCiCB/o07FuUmTLDnB9zxhAYHZOz6gWROYvdFZUrZXztBAoTZaafz9s0DzQfaxxA5d0G1dPV5PER9MWReqQX5hDYwLSbFYYhSehLcOetj6+W6qVC8dOJvYGh3aJjlleLy/luROj1TQsZTmv1d6W/Pg+czwa4Z5C3zmo+FxAHCueUvdZoE2/ojHG/4gig1/pFWB2K/HTIPZRvqvoTk3OmL7mYhAaEYfc2LYc2D1x+5lg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
