travis:
  secure:
    BINSTAR_TOKEN: wtsOofbJMvOTswX/5bzMRN7fENyiCBwd5dodLw7LV5pcNPUK3ur9FvoIxiHXsesKjbus61EOzS1hahatx6EcgRNAmhb2AP/v0+jz46sLYdkvzieNzbyDYS9hHblGOSvUzy3iXf35gQBT+xX4YTIzun5N0drAX+Z2zOu67Iq1az5YMxRQgnFc9awrdLglfc649M7GfcGQzz+/MdNxeGD34N2kILjuvUl+mvJcvctWf6qKAq7sCOsAmaT2yUWyofsRhKVSbc2/a0vRJBBDvjj15gqZtsfOYT81Q+gV6qhseY6xholcGjgUQLxWHrquH3wQpzonsd9C8nOWdHArwq949JqKs/JPBEEIjIwh+uLQIryaDv0rGxWs7Rt4f6VcwrxdBYjiHeELxSwiky3nfHGlTZSwP/BkoOkYZPUF+sskQUiU41ixJxVNjgQK+fUb/9oYeK3Ocfe5H+jlVYyIhoqYOGcp+Qx/Aq+13ptkgxvLhfJdNsmK4YXeN0Qw7ynjcmcJZ5PJogr9ZmzkH0XEa94l29BsxVZehQm7x8h5KGw57LS+MaJlBP8Wi8YBixQwemyFaVECw4WOBlPKFXW6U31F1Af+kPGxfOiIl8l+GNbrhkuJZztcKqQyQETkyA6m+Hwd0lEXA7+rsVU4uYh8ReR0xJylFpMj7cwB6olGYeABMlA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
